package com.thallyson.sboot.payrollqueryservice;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import java.sql.DriverManager;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

class PayrollTenantMigrationTest {

    @Test
    void expandsLegacySchemaWithoutAssigningFictitiousTenant() throws Exception {
        String url = "jdbc:h2:mem:legacy_payroll;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "");
             var statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE payroll (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        employee_id VARCHAR(100) NOT NULL,
                        payroll_date DATE NOT NULL,
                        gross_salary DECIMAL(19,2) NOT NULL,
                        deductions DECIMAL(19,2) NOT NULL,
                        net_salary DECIMAL(19,2) NOT NULL
                    )
                    """);
            statement.execute("""
                    INSERT INTO payroll(employee_id, payroll_date, gross_salary, deductions, net_salary)
                    VALUES ('legacy-employee', DATE '2026-07-01', 1000.00, 200.00, 800.00)
                    """);
        }

        Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .load()
                .migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "");
             var result = connection.createStatement().executeQuery(
                     "SELECT company_id, net_salary FROM payroll WHERE employee_id='legacy-employee'")) {
            assertThat(result.next()).isTrue();
            assertThat(result.getString("company_id")).isNull();
            assertThat(result.getBigDecimal("net_salary")).isEqualByComparingTo(new BigDecimal("800.00"));
        }

        try (var connection = DriverManager.getConnection(url, "sa", "");
             var result = connection.createStatement().executeQuery(
                     "SELECT \"version\", \"success\" FROM \"flyway_schema_history\" "
                             + "WHERE \"type\" = 'BASELINE'")) {
            assertThat(result.next()).isTrue();
            assertThat(result.getString("version")).isEqualTo("0");
            assertThat(result.getBoolean("success")).isTrue();
            assertThat(result.next()).isFalse();
        }

        try (var connection = DriverManager.getConnection(url, "sa", "");
             var result = connection.createStatement().executeQuery(
                     "SELECT \"version\" FROM \"flyway_schema_history\" "
                             + "WHERE \"type\" = 'SQL' ORDER BY \"installed_rank\"")) {
            assertThat(result.next()).isTrue();
            assertThat(result.getString("version")).isEqualTo("1");
            assertThat(result.next()).isTrue();
            assertThat(result.getString("version")).isEqualTo("2");
            assertThat(result.next()).isTrue();
            assertThat(result.getString("version")).isEqualTo("3");
            assertThat(result.next()).isFalse();
        }
    }
}
